name: selfcheck
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_fonts:
  cupertino_icons:
  flutter_tts:
  percent_indicator:
  audioplayers:
  http:
  path_provider:
  cached_network_image:
  pie_chart:
  # youtube_player:
  smooth_star_rating:
  cloud_firestore: ^0.13.7
  provider: ^4.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.JPG"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



  #  Assets (Images)
  assets:
    - assets/images/HappyAddaLogo.png
    - assets/images/books.jpg
    - assets/images/pb6/gaurd.png
    - assets/images/pb6/spinach.png
    - assets/images/pb6/eggplant.png
    - assets/images/pb6/jackfruit.png
    - assets/images/well_done.png
    - assets/images/quiz.png
    - assets/images/self_learning.jpg

  # Assets (Sounds)
    - assets/audio/parrot.mp3
    - assets/audio/monkey.mp3
    - assets/audio/horse.mp3
    - assets/audio/dog.mp3
    - assets/audio/cat.mp3
    - assets/audio/pig.mp3
    - assets/audio/cuckoo.mp3
    
  # Fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: GloriaHallelujah
      fonts:
        - asset: assets/fonts/Gloria_Hallelujah/GloriaHallelujah-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 800
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 100
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 700

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Light.ttf  
          weight: 100
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf         
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf         
          weight: 800
        # - asset: assets/fonts/Nunito/Nunito-Italic.ttf
        # - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
        # - asset: assets/fonts/Nunito/Nunito-Black.tt
        # - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
        # - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.tt
        # - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
        # - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
        # - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
        # - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
